### ISSUE TITLE
Adjust release pipeline of existing curricula and update them

### ISSUE THREAD

**Issue by aheusingfeld** [isaqb-org/advanced-template#58]
## Released Asciidoc Curricula
- [x] [Foundation Level](https://github.com/isaqb-org/curriculum-foundation)
- [x] [ADOC](https://github.com/isaqb-org/curriculum-adoc)
- [x] [ARCEVAL](https://github.com/isaqb-org/curriculum-arceval)
- [x] [BLOCKCHAIN](https://github.com/isaqb-org/curriculum-blockchain)
- [x] [EMBEDDED](https://github.com/isaqb-org/curriculum-embedded)
- [x] [FLEX](https://github.com/isaqb-org/curriculum-data) (_RELEASE CANDIDATE_)
- [x] [FUNAR](https://github.com/isaqb-org/curriculum-funar)
- [x] [IMPROVE](https://github.com/isaqb-org/curriculum-improve)
- [x] [REQ4ARC](https://github.com/isaqb-org/curriculum-req4arc)
- [x] [WEB](https://github.com/isaqb-org/curriculum-web)
- [x] [WEBSEC](https://github.com/isaqb-org/curriculum-websec)

## Currently in Preparation for Asciidoc
- [x] [CLOUDINFRA](https://github.com/isaqb-org/curriculum-cloudinfra)
- [x] [DATA](https://github.com/isaqb-org/curriculum-data)
- [x] [DDD](https://github.com/isaqb-org/curriculum-ddd)
- [x] [EAM](https://github.com/isaqb-org/curriculum-eam)
- [x] [SOFT](https://github.com/isaqb-org/curriculum-soft)
 
## Currently Not Available in Asciidoc
We don't actually care about non-released ones, as they'll be released from a new template, no changes necessary.

- [x] ~~AGILA~~
- [x] ~~SOA-T~~
- [x] ~~SWAM~~

**Comment by programming-wolf** [comment]
### Necessary steps for existing modules:
- [x] Adjust new Date (English, German) in `build.gradle`
- [x] Add learningGoals script and include
- [x] Remove everything related to FEEDBACK
- [x] Adjust file suffix (- instead of _)
- [x] Update file structure (just one file for all learning goals per chapter)
- [x] Remove everything related to Travis
- [x] Update pdftheme
- [x] Update Gradle and asciidoctor version
- [x] Add .github folder for GitHub actions
- [x] Adjust build URL in Readme and Index.adoc
- [x] Add improved translation
- [x] Add fixes for learning goal intro and required competences
- [x] Add gh-pages branch

### Necessary Steps for New Modules
- [ ] Create new repository
- [ ] ~After creating a clone of the template, [fix PDF-Theme (submodule)](https://github.com/isaqb-org/advanced-template/issues/60#issuecomment-616407980)~
- [ ] Adjust URLs in Readme/Index files to point to the particular module's URLs
- [ ] Let curators create a short info text for README
- [ ] Add module to https://github.com/isaqb-org/isaqb-org.github.io
- [ ] Add gh-pages branch

**Comment by programming-wolf** [comment]
All modules currently in asciidoc have the latest changes, so we can close this issue (FINALLY!!).
