### ISSUE TITLE
Add Support for Release Candidates

### ISSUE THREAD

**Issue by programming-wolf** [isaqb-org/advanced-template#85]
In addition to regular releases and PR builds, we need to support Git tags that define a Release Candidate. This is required at least for the Foundation Curriculum. 

### TODOs
- [ ] add GitHub action to build RC-Tags, regardless of the branches that they are created on
- [ ] RC-Tags are supposed to create pre-releases
- [ ] Pre-releases must not be published to GitHub pages (for now)
- [ ] Tag example: 2020.1-RC1
